### ISSUE TITLE
Failing doctests in README.rst

### ISSUE THREAD

**Issue by cutz** [OpenNTI/nti.recipes.zcml#1]
When running the tests with `nosetests`  we are getting a failure from one of the doctests defined in the README file.

```bash
+ ../../bin/python setup.py nosetests --with-coverage --cover-inclusive --with-xunit
running nosetests
running egg_info
writing requirements to src/nti.recipes.zcml.egg-info/requires.txt
writing src/nti.recipes.zcml.egg-info/PKG-INFO
writing namespace_packages to src/nti.recipes.zcml.egg-info/namespace_packages.txt
writing top-level names to src/nti.recipes.zcml.egg-info/top_level.txt
writing dependency_links to src/nti.recipes.zcml.egg-info/dependency_links.txt
writing entry points to src/nti.recipes.zcml.egg-info/entry_points.txt
reading manifest file 'src/nti.recipes.zcml.egg-info/SOURCES.txt'
writing manifest file 'src/nti.recipes.zcml.egg-info/SOURCES.txt'
F
======================================================================
FAIL: Doctest: README.rst
----------------------------------------------------------------------
AssertionError: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for README.rst
  File "/Users/Shared/Jenkins/Home/workspace/nti.dataserver-buildout/sources/nti.recipes.zcml/src/nti/recipes/zcml/tests/README.rst", line 0

----------------------------------------------------------------------
File "/Users/Shared/Jenkins/Home/workspace/nti.dataserver-buildout/sources/nti.recipes.zcml/src/nti/recipes/zcml/tests/README.rst", line 75, in README.rst
Failed example:
    print 'start', system(buildout) # doctest:+ELLIPSIS
Differences (ndiff with -expected +actual):
    + start Getting distribution for 'setuptools'.
    + Got setuptools 36.5.0.
    + Upgraded:
    +   setuptools version 36.5.0;
    + restarting.
    + Generated script '/private/var/folders/l_/f5r4sbjj4pl5d3qljbs77qmm000088/T/tmpmjCbp7buildoutSetUp/_TEST_/sample-buildout/bin/buildout'.
    - start Installing test1.
    ? ------
    + Installing test1.
    + /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
    +   warnings.warn(msg)
    + warning: no files found matching '*' under directory 'setuptools/_vendor'
      While:
        Installing test1.
    - Error: The parents of '/.../sample-buildout/zope/etc/package-includes' do not exist
    + Error: The parents of '/private/var/folders/l_/f5r4sbjj4pl5d3qljbs77qmm000088/T/tmpmjCbp7buildoutSetUp/_TEST_/sample-buildout/zope/etc/package-includes' do not exist
    + <BLANKLINE>
```

This looks to have been failing for about 4 months.

**Comment by jamadden** [comment]
Yikes. Why are we still using `nosetests` here? We really should update that.

We need to add a .travis.yml and actually push an artifact to PyPI too.

**Comment by cutz** [comment]
> Yikes. Why are we still using nosetests here? We really should update that.

I'm guessing this project just hasn't been updated.  Most things are running using `nose2`.  There is a bit of smarts in the test scripts that use `nose2` or `nosetests` conditionally based on how the project looks setup.  

If `nose2.cfg` exists we use something of the form `../../bin/nose2 --with-cov --plugin nose2.plugins.junitxml --junit-xml`

else if `setup.py` exists we use the form `../../bin/python setup.py nosetests --with-coverage --cover-inclusive --with-xunit`

IIRC this is carry over from several iterations of tests scripts ago.  Maybe there is a more appropriate way?

**Comment by papachoco** [comment]
Not all of the internal projects have an update .travis files.  As @jamadden  we should switch to zope testrunner.

**Comment by jamadden** [comment]
> I'm guessing this project just hasn't been updated.

I'll update it.

> If nose2.cfg exists we use something of the form ../../bin/nose2 --with-cov --plugin nose2.plugins.junitxml --junit-xml

> else if setup.py exists we use the form ../../bin/python setup.py nosetests --with-coverage --cover-inclusive --with-xunit

> IIRC this is carry over from several iterations of tests scripts ago. Maybe there is a more appropriate way?

I do not recommend either nose or nose2:

- nose is not maintained
- nose2 is buggy, especially when it comes to layers.
- both of them have issues correctly measuring coverage (for example, they fail to make any kind of report for files that aren't imported, they have a weird set of implicit defaults for what is/not considered, etc)
- They don't render tracebacks very well (don't respect `__traceback_info__` or `__traceback_supplement__`) (There is a plugin for nose, [nti.nose_traceback_info](https://pypi.python.org/pypi/nti.nose_traceback_info), but it's not maintained.)

`zope.testrunner` is the way to go. `coverage run -m zope.testrunner` is the way to measure coverage.

**Comment by cutz** [comment]
>`zope.testrunner` is the way to go 

There may be a more appropriate place for this conversation, but with a move to zope.testrunner we'll need to figure out how to get test output in junit formatted xml or some other format that can be easily converted in to that. The automated test pipeline relies on that at this point.

**Comment by jamadden** [comment]
[collective.xmltestreport](https://github.com/collective/collective.xmltestreport) handles that.
